version: 1
update_configs:
  - package_manager: go:modules
    directory: /
    update_schedule: daily
    default_reviewers:
      - "syou6162"
  - package_manager: javascript
    directory: /
    update_schedule: weekly
    default_reviewers:
      - "syou6162"
