name: CI

on: [push]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup vars
      id: vars
      run: |
        docker_image_repo="${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.AWS_ECR_REPOSITORY_NAME }}"
        branch_pretty_name="$(echo "${GITHUB_REF#refs/heads/}" | sed "s/[^a-zA-Z0-9_-]/-/g")"
        echo "::set-output name=commit_tag::${docker_image_repo}:commit-${{ github.sha }}"
        echo "::set-output name=branch_tag::${docker_image_repo}:branch-${branch_pretty_name}"
        echo "::set-output name=release_tag::${docker_image_repo}:release-${branch_pretty_name}-${{ github.sha }}"
    - name: Build image
      run: docker build -f Dockerfile.api -t ${{ steps.vars.outputs.commit_tag }} .
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ECR_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_ECR_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    - name: Login to ECR
      uses: aws-actions/amazon-ecr-login@v1
      env:
        AWS_REGION: ${{ secrets.AWS_REGION }}
    - name: Push to ECR
      run: |
        docker push ${{ steps.vars.outputs.commit_tag }}
        docker tag ${{ steps.vars.outputs.commit_tag }} ${{ steps.vars.outputs.branch_tag }}
        docker push ${{ steps.vars.outputs.branch_tag }}
    - name: Push release tag to ECR
      run: |
        docker tag ${{ steps.vars.outputs.commit_tag }} ${{ steps.vars.outputs.release_tag }}
        docker push ${{ steps.vars.outputs.release_tag }}
